### ISSUE TITLE
Project - number of participants in team

### ISSUE THREAD

**Issue by Yothu** [Yothu/space-travelers-hub#25]
Quantity of participants: 2

Check the project for this repo [here](https://github.com/Yothu/space-travelers-hub/projects/1).

**Comment by Mihndim2020** [comment]
### Hi Team, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark: Required information provided in the GitHub issue. 

There are some issues that you still need to work on to get this project approved, but you are almost there!
![ALMOST-MINION](https://user-images.githubusercontent.com/65852621/133680327-431cb21d-ad7c-483a-84eb-21b733980a04.png)

# Status: Requires Changes ♻️
_Check the comments below the review._

- [x] Since there are only two of you in the group, all cards with `Team3` prefix should be removed.  `Number of cards in Backlog should be equal to 17.`
- [x] Please make sure all cards are assigned to team members and tasks are distributed in a fairway.
- [x] Kindly make sure each team member has cards with all required categories.

* Required categories:`Setup`, `Fetch data`, `Lists render`, `Actions`, `Conditional components`, `Filters`


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MahmoudBakr23** [comment]
Hi Team😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Yothu** [comment]
Thanks for the review!
